// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-contatos.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sb() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_contatos_default = defineTool({
  name: "search_contatos",
  title: "Search contatos",
  description: "Search CRM contacts by name or phone. Returns up to `limit` matches.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Name or phone fragment to search for."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const { data, error } = await sb().from("contatos").select("id, nome, telefone, status_funil, ultima_interacao").or(`nome.ilike.%${query}%,telefone.ilike.%${query}%`).order("ultima_interacao", { ascending: false, nullsFirst: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { contatos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-recent-messages.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sb2() {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_recent_messages_default = defineTool2({
  name: "get_recent_messages",
  title: "Get recent messages",
  description: "Fetch the most recent WhatsApp messages for a given contato_id, newest first.",
  inputSchema: {
    contato_id: z2.string().uuid().describe("Contato UUID."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max messages (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ contato_id, limit }) => {
    const { data, error } = await sb2().from("mensagens").select("id, direcao, mensagem, type, timestamp, status").eq("contato_id", contato_id).order("timestamp", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sb3() {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_orders_default = defineTool3({
  name: "list_orders",
  title: "List orders",
  description: "List recent orders, optionally filtered by customer telefone (E.164 digits only).",
  inputSchema: {
    telefone: z3.string().trim().optional().describe("Optional E.164 digits-only phone filter."),
    limit: z3.number().int().min(1).max(100).optional().describe("Max orders (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ telefone, limit }) => {
    let q = sb3().from("orders").select("id, telefone, valor_total, data_pedido, bling_id, produtos").order("data_pedido", { ascending: false }).limit(limit ?? 20);
    if (telefone) q = q.eq("telefone", telefone);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/pipeline-summary.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sb4() {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var pipeline_summary_default = defineTool4({
  name: "pipeline_summary",
  title: "Pipeline summary",
  description: "Return counts of contatos grouped by status_funil (CRM pipeline stage).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const { data, error } = await sb4().from("contatos").select("status_funil");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const counts = {};
    for (const r of data ?? []) {
      const k = r.status_funil ?? "unknown";
      counts[k] = (counts[k] ?? 0) + 1;
    }
    return {
      content: [{ type: "text", text: JSON.stringify(counts) }],
      structuredContent: { counts }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "flowcrm-mcp",
  title: "FlowCRM MCP",
  version: "0.1.0",
  instructions: "Read-only tools for the FlowCRM WhatsApp CRM. Use `search_contatos` to find a contact, `get_recent_messages` for their chat history, `list_orders` for purchases, and `pipeline_summary` for funnel counts.",
  tools: [search_contatos_default, get_recent_messages_default, list_orders_default, pipeline_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
